version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo "Installing jq..."
      - curl -qL -o jq https://github.com/jqlang/jq/releases/download/jq-1.6/jq-linux64 && chmod +x ./jq
      - echo Executing Terraform phase
      - wget https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
      - unzip terraform_1.9.5_linux_amd64.zip
      - ls -lrt
      - mv terraform /bin
      - terraform -v
      - cd $CODEBUILD_SRC_DIR
      - cd $CODEBUILD_SRC_DIR/c3ops_core_infra_prod/
      - echo "Configuring AWS credentials"
      - aws sts get-caller-identity  
      - terraform -v
      - terraform init
      - terraform fmt 
      - terraform validate
  build:
    commands:
      - echo Executing build phase
      - ls -lt $CODEBUILD_SRC_DIR
      - terraform plan -lock=false 
      #- terraform apply -auto-approve -lock=false 
  post_build:
    commands:
      - echo post build phase
      - echo "Nothing to Execute on post build"
      - echo "Build completed on `date`"





