---
- name: Install CloudWatch Agent
ansible.builtin.dnf:
name: amazon-cloudwatch-agent
state: present


- name: Place CloudWatch Agent config
ansible.builtin.template:
src: cloudwatch-agent.json.j2
dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
mode: "0644"
notify: Restart cloudwatch agent