---
- name: Install CloudWatch Agent
ansible.windows.win_chocolatey:
name: amazon-cloudwatch-agent
state: present


- name: Place CloudWatch config
ansible.windows.win_template:
src: cloudwatch-agent.json.j2
dest: C:\ProgramData\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent.json


- name: Restart CloudWatch Agent
ansible.windows.win_command: >
powershell -ExecutionPolicy Bypass -File "C:\Program Files\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent-ctl.ps1" -a restart -m ec2 -c file:C:\ProgramData\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent.json
