---
- name: Update packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install base utilities
  ansible.builtin.dnf:
    name:
      - unzip
      - jq
      - curl
      - wget
      - bind-utils
      - git
    state: present

- name: Ensure SSM agent running
  ansible.builtin.service:
    name: amazon-ssm-agent
    state: started
    enabled: true

- name: Create app user
  ansible.builtin.user:
    name: "{{ app_user }}"
    state: present

- name: Passwordless sudo for app user
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ app_user }}"
    content: "{{ app_user }} ALL=(ALL) NOPASSWD:ALL\n"
    mode: "0440"
